sudo: required

language: generic

services:
  - docker

before_install:
  - docker pull shinesolutions/aem-platform-buildenv

script:
  - docker run --rm --workdir /opt/workspace -v `pwd`:/opt/workspace -i -t shinesolutions/aem-platform-buildenv bash -c "make ci"
