source 'http://rubygems.org'

gem 'json'
gem 'json_pure', '~> 1.8'
gem 'puppet', '~> 4.4.0'
gem 'puppetlabs_spec_helper', '>= 0.1.0'
gem 'puppet-lint', '>= 0.3.2'
gem 'puppet-lint-param-docs'
gem 'puppet-lint-strict_indent-check'
gem 'metadata-json-lint', '= 1.0.0'
gem 'facter'
gem 'hiera'
gem 'rspec-puppet', '= 2.5.0'
gem 'rake'
